# Generated by Django 4.1.2 on 2022-11-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_client',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
