# Generated by Django 4.1.2 on 2022-12-16 08:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
