# Generated by Django 4.1.2 on 2022-12-16 11:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
