# Generated by Django 4.1.2 on 2022-11-23 10:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
