# Generated by Django 4.1.2 on 2022-12-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.secteur'),
        ),
    ]
