# Generated by Django 4.1.2 on 2022-12-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_is_seller_alter_profile_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_seller',
            new_name='is_seller_entreprie',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_seller_individual',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
