# Generated by Django 4.1.2 on 2022-12-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_is_seller_profile_is_seller_entreprie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_seller_entreprie',
            new_name='is_seller_entreprise',
        ),
    ]
