# Generated by Django 4.1.2 on 2022-12-23 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_societe_num_rcs_alter_societe_gerant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.categorie'),
        ),
    ]
