# Generated by Django 4.1.2 on 2022-12-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
