# Generated by Django 4.1.2 on 2023-01-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_alter_proprietes_options_alter_typepropriete_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietes',
            name='rental_mode',
            field=models.CharField(blank=True, choices=[('moi', 'Par mois'), ('jou', 'Par jour'), ('ann', 'Par année')], max_length=3, null=True),
        ),
    ]
