# Generated by Django 4.1.2 on 2023-01-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_proprietes_options_alter_proprietes_rental_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietes',
            name='rental_mode',
            field=models.CharField(blank=True, choices=[('jou', 'Par jour'), ('moi', 'Par mois'), ('ann', 'Par année')], max_length=3, null=True),
        ),
    ]
